//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMVACChemical.Services.ServiceResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMVACChemical.Services.ServiceResource.ServiceResource", typeof(ServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apikey.
        /// </summary>
        public static string apikey {
            get {
                return ResourceManager.GetString("apikey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        public static string applicationjson {
            get {
                return ResourceManager.GetString("applicationjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.trackabout.com:443/api/assets/bySerial.
        /// </summary>
        public static string aseetsAPIBySerialNumber {
            get {
                return ResourceManager.GetString("aseetsAPIBySerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets.
        /// </summary>
        public static string assetApiChar {
            get {
                return ResourceManager.GetString("assetApiChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://trackabout.com:443/api/assets.
        /// </summary>
        public static string assetsAPI {
            get {
                return ResourceManager.GetString("assetsAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://trackabout.com:443/api/locations/byMId.
        /// </summary>
        public static string assetsLocationAPI {
            get {
                return ResourceManager.GetString("assetsLocationAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://trackabout.com:443/api/deliveries.
        /// </summary>
        public static string assetToCustomerLocation {
            get {
                return ResourceManager.GetString("assetToCustomerLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.trackabout.com:443/api/customers.
        /// </summary>
        public static string customersVisibleListAPI {
            get {
                return ResourceManager.GetString("customersVisibleListAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-ddTHH:mm:ssK.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://trackabout.com:443/api/fills.
        /// </summary>
        public static string fillsApi {
            get {
                return ResourceManager.GetString("fillsApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.trackabout.com:443/api/locations.
        /// </summary>
        public static string listofAllLocationAPI {
            get {
                return ResourceManager.GetString("listofAllLocationAPI", resourceCulture);
            }
        }
    }
}
